### PR TITLE
SQL Concurrent Tests (partial)

### PR DESCRIPTION
**Pull request by jrolli**
This is a partial implementation of the planned test suite for concurrent SQL tests (#2).  The current code base will fail this test (possibly not on Travis due to low concurrency) which is why I would like to merge these simple tests now so that we can fix the current issue and identify any regressions in the future.

### CODE REVIEW

**Comment by yangjuns** [comment]
Travis failed?

**Comment by jrolli** [comment]
This PR should be on hold until the race condition addressed by #19 is merged.

**Review by yangjuns — COMMENTED** [review]
The concurrent Insert and Select tests look reasonable to me. The only thing I would suggest is to increase the number of iterations to maybe 100 because 5 seems too small to me

**Comment by jrolli** [comment]
Increased the number of iterations.  It raises the run time of each test to approximately 2 seconds (with ASAN enabled), but this should not explode on smaller machines since the work is proportional to the number of hardware threads used.

Ready for final review and merging.

**Pull request merged**
